import { Inter as FontSans} from 'next/font/google'
import { cn } from "cva"
import '@/styles/globals.css'
import NavBar from '@/components/MainNavBar.tsx'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: "--font-sans"
})

interface RootLayoutProps {
  children: React.ReactNode
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { RootLayoutProps}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={fontSans.className}>
        <NavBar />
        <nav>
          <p>Navbar</p>
        </nav>
        {children}
      </body>
    </html>
  )
}